=== jiremv/preguntas/clase.dtd
<?xml encoding="iso-8859-1"?>
<!-- Fichero de definción de cada pregunta -->
<!ELEMENT p (q0*, g0*, q, g*, q2*, g2*,as, x, t*, i*, x2*, i2*, v1*, d1*, v2*, d2*, v3*, d3*, v4*, d4*, v5*, d5*, v6*, d6*, v7*, d7*)>
<!ELEMENT q0 (#PCDATA)>
<!ELEMENT g0 (#PCDATA)>
<!ELEMENT q (#PCDATA)>
<!ELEMENT g (#PCDATA)>
<!ELEMENT q2 (#PCDATA)>
<!ELEMENT g2 (#PCDATA)>
<!ELEMENT as (a)+>
<!ATTLIST as
	r CDATA #REQUIRED
	correcta CDATA #REQUIRED
>
<!ELEMENT a (#PCDATA)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT t (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT x2 (#PCDATA)>
<!ELEMENT i2 (#PCDATA)>
<!ELEMENT v1 (#PCDATA)>
<!ELEMENT d1 (#PCDATA)>
<!ELEMENT v2 (#PCDATA)>
<!ELEMENT d2 (#PCDATA)>
<!ELEMENT v3 (#PCDATA)>
<!ELEMENT d3 (#PCDATA)>
<!ELEMENT v4 (#PCDATA)>
<!ELEMENT d4 (#PCDATA)>
<!ELEMENT v5 (#PCDATA)>
<!ELEMENT d5 (#PCDATA)>
<!ELEMENT v6 (#PCDATA)>
<!ELEMENT d6 (#PCDATA)>
<!ELEMENT v7 (#PCDATA)>
<!ELEMENT d7 (#PCDATA)>

=== jiremv/preguntas/nom/1primaria/100-200_2018/nom-pri-1184.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
	<q0>
	</q0>
	<g0>./../../preguntas/nom/1primaria/100-200_2018/nom-pri-1184-p.png
	</g0>
	<q>Durante la experiencia, una pareja de estudiantes propone lo siguiente:
	</q>
	<g0>./../../preguntas/nom/1primaria/100-200_2018/nom-pri-1184-p2.png
	</g0>
	<q2>En la propuesta de los estudiantes, ¿qué tipo de variable corresponde al material de los
vasos?	
	</q2>
	<as r="R" correcta="0">
		<a>Independiente</a>
		<a>Dependiente</a>
		<a>Interviniente</a>
	</as>	
	<x>A.</x>
	<i></i>
	<x2>
	</x2>
	<i2></i2>
	<v></v>
</p>

=== jiremv/preguntas/nom/0inicial/300-400/nom-ini-313.xml
<?xml version='1.0' encoding='iso-8859-1'?> 
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
    <q>Melissa, profesora del aula de 5 años, considera que la evaluación es permanente porque se realiza durante
    todo el año. Dentro de la evaluación que realiza a sus alumnos encuentra que Rosita presenta dificultades para 
    socializar, juega sola, evade los juegos grupales, y también se resiste a responder preguntas.
Esta situación afecta su aprendizaje. ¿Cuál es la conclusión acerca del comportamiento de Rosita y qué necesita para lograr 
mejoras en su aprendizaje?</q>
    <as r="R" correcta="2">
        <a>Rosita es una niña que tiene problemas en su hogar y necesita desarrollar capacidades de confianza y seguridad para 
lograr afirmar su identidad y su sentimiento de pertenencia al grupo social.</a>
        <a>Rosita muestra una conducta retraída por agresiones constantes recibidas en su familia, necesita recibir afecto para 
afirmar su autoestima y desarrollarse armoniosamente.</a>
        <a>Rosita es una niña tímida que necesita desarrollar capacidades de confianza y seguridad para lograr afirmar su identidad 
y su sentimiento de pertenencia a un grupo social.</a>
        <a>Rosita carece de apoyo de sus pares y necesita fortalecer la comunicación activa de su entorno, participar en reuniones
sociales, compartir juegos grupales.</a>
    </as>
    <x>C.</x>
</p>

=== jiremv/preguntas/nom/5comunicacion/200-300_2019/nom-com-5283.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
  <q0>Antes de empezar a escribir su texto, un grupo de estudiantes le ha pedido al docente que revise el avance que se
      presenta a continuación:</q0>
  <g0>5283-p.png</g0>
  <q>El docente nota que los estudiantes han tenido en cuenta diversos aspectos correspondientes al proceso de
     planificación de textos. ¿Cuál de estos aspectos se evidencia en el avance presentado por el grupo de estudiantes?</q>
  <g></g>
  <q2></q2>
  <g2></g2>
  <as r="R" correcta="2">
    <a>Tomar como base diversas fuentes de información para la escritura de su texto.</a>
    <a>Seleccionar un registro de lenguaje adecuado en función del destinatario.</a>
    <a>Utilizar la estructura de un género textual que se ajusta a la situación.</a>
  </as>
  <x>C</x>
  <i></i>
  <x2></x2>
  <i2></i2>
  <v1></v1>
</p>

=== jiremv/preguntas/nom/0inicial/300-400/19.xml
<?xml version='1.0' encoding='iso-8859-1'?> 
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
    <q>La profesora Margot como parte de su planificación del área de Matemática pretende que los niños a través
    de situaciones vivenciales, aprendan a realizar agrupaciones de diversos elementos que lo rodean.
¿Qué debe planificar de manera específica?</q>
    <as r="R" correcta="2">
        <a>Un proyecto de aprendizaje matemático</a>
        <a>Una secuencia de pensamiento matemático</a>
        <a>Una sesión de aprendizaje sobre clasificación</a>
        <a>Una sesión de psicomotricidad con materiales concretos</a>
    </as>
    <x>C.</x> <v1></v1>
</p>

=== jiremv/preguntas/nom/1primaria/400/nom-pri-1609.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
    <q0>Los estudiantes de 3° grado trabajan el proyecto "Cuidemos el agua". Luego de muchas propuestas de
                actividades, acordaron elaborar un afiche, con la finalidad de motivar la toma de conciencia sobre el
                cuidado y conservación del agua. Para la elaboración del afiche la docente sugirió que, en equipos
                determinaran el tema, los posibles destinatarios, el estilo, la estructura interna del texto, etc.</q0>
    <g0></g0>
    <q>¿Cuáles de las siguientes actividades corresponden al proceso de producción total del afiche?</q>
    <as r="R" correcta="1">
        <a>Evaluación de la coherencia y etilo del texto.</a>
        <a>Escritura preliminar, revisión y publicación.</a>
        <a>Revisión del estilo y del aspecto formal del texto.</a>
        <a>Revisión de la ortografía, cohesión y coherencia.</a>
    </as>
    <x>B.</x>
</p>

=== jiremv/preguntas/nom/7trabajo/200-300_2019/21.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
    <q0>Un equipo de estudiantes está implementando la fase de distribución y venta de los productos de su proyecto. La
        entrega del producto se hace a domicilio y el pago se realiza contra entrega. Los repartidores en varias
        ocasiones han retornado con el producto porque los clientes manifiestan que ya se desanimaron de adquirirlo. Con
        el propósito de encontrar una solución, uno de los estudiantes ha sugerido lo siguiente: "Propongo que el
        cliente, primero, pague el precio de lo que va a comprar y, luego, le entregamos su producto".</q0>
    <g0></g0>
    <q>¿Cuál de los siguientes aspectos de la técnica SCAMPER corresponde a la propuesta del estudiante?</q>
    <g></g>
    <q2></q2>
    <g2></g2>
    <as r="R" correcta="2">
        <a>Sustituir (S).</a>
        <a>Modificar (M).</a>
        <a>Reordenar (R).</a>
    </as>
    <x>C</x>
    <i></i>
    <x2></x2>
    <i2></i2>
    <v></v>
</p>

=== jiremv/preguntas/nom/5comunicacion/500/nom-com-5413.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
	<q0>
	</q0>
	<g0>
	</g0>
<q>Presentan vicios de dicción:
</q>
	<g>./../preguntas/nom/5comunicacion/500/nom-com-5413-p.png
	</g>
<as r="R" correcta="4">
<a>I-III</a>
<a>II-III</a>
<a>I-IV</a>
<a>III-IV</a>
<a>I-III-IV</a>
</as>
<x>E.</x><x2></x2>
</p>

=== jiremv/preguntas/nom/10histgeoecon/200-300_2019/nom-hge-10265.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
	<q0>El propósito de un docente es que los estudiantes reconozcan la relevancia histórica de las ideas y propuestas de Martin Luther King a favor de los derechos civiles de la población afrodescendiente en EE. UU. </q0>
	<g0>¿Cuál de las siguientes actividades es más adecuada para alcanzar el propósito planteado?
</g0>
	<q></q>
   <g></g>
	<q2></q2>
   <g2></g2>
	<as r="R" correcta="1">
		<a>Pedir a los estudiantes que busquen información sobre los postulados de Martin Luther King contra el segregacionismo en EE. UU. en los años sesenta. Luego, solicitarles que describan el liderazgo que ejerció en algunos movimientos sociales de la época. Por último, pedirles que expliquen cómo sus ideas han influido en los movimientos sociales de la actualidad. </a>
		<a>Pedir a los estudiantes que busquen información sobre los movimientos sociales a favor de los derechos civiles en América Latina en el siglo XX. Luego, solicitarles que los ubiquen en una línea de tiempo. Por último, pedirles que identifiquen cuáles son los movimientos sociales latinoamericanos que coincidieron temporalmente con el movimiento social que lideró Martin Luther King.  </a>
		<a>Pedir a los estudiantes que busquen información acerca de la situación de la población afrodescendiente durante las décadas del cincuenta y sesenta en EE. UU. Luego, solicitarles que identifiquen los casos más mediáticos de segregacionismo en ese país durante las décadas mencionadas. Por último, pedirles que expliquen cómo dicho contexto influyó en los postulados de Martin Luther King a favor de los derechos civiles.</a>
	</as>
	<x>B</x>
	<i></i>
	<x2>
	</x2>
	<i2></i2>
	<v></v>
</p>
