=== jiremv/preguntas/clase.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="p">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="q0"/>
        <xs:element type="xs:string" name="g0"/>
        <xs:element type="xs:string" name="q"/>
        <xs:element type="xs:string" name="g"/>
        <xs:element type="xs:string" name="q2"/>
        <xs:element type="xs:string" name="g2"/>
        <xs:element type="xs:string" name="q3"/>
        <xs:element type="xs:string" name="g3"/>
        <xs:element type="xs:string" name="q4"/>
        <xs:element type="xs:string" name="g4"/>
        <xs:element type="xs:string" name="q5"/>
        <xs:element type="xs:string" name="g5"/>
        <xs:element name="as">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="a" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="r" use="required"/>
            <xs:attribute type="xs:string" name="correcta" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:string" name="x"/>
        <xs:element type="xs:string" name="t"/>
        <xs:element type="xs:string" name="i"/>
        <xs:element type="xs:string" name="x2"/>
        <xs:element type="xs:string" name="i2"/>
        <xs:element type="xs:string" name="v1"/>
        <xs:element type="xs:string" name="d1"/>
        <xs:element type="xs:string" name="v2"/>
        <xs:element type="xs:string" name="d2"/>
        <xs:element type="xs:string" name="v3"/>
        <xs:element type="xs:string" name="d3"/>
        <xs:element type="xs:string" name="v4"/>
        <xs:element type="xs:string" name="d4"/>
        <xs:element type="xs:string" name="v5"/>
        <xs:element type="xs:string" name="d5"/>
        <xs:element type="xs:string" name="v6"/>
        <xs:element type="xs:string" name="d6"/>
        <xs:element type="xs:string" name="v7"/>
        <xs:element type="xs:string" name="d7"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jiremv/preguntas/nom/1primaria/400-500/61.xml
<?xml version="1.0" encoding="UTF-8" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

    <q0>Peter expresa la intención de su sesión de aprendizaje: "Que los niños y niñas del 6° grado, a partir de
                las estrategias de producción de textos, aprendan a bosquejar una ficha de entrevista, para investigar
                con sus familiares, autoridades y vecinos sobre la celebración de la Semana Santa en su comunidad".</q0>
    <g0></g0>
    <q>Peter sabe que los propósitos de los aprendizajes son importantes, sobre todo si lo trabajamos con los
               niños(as) para el ejercicio de la ciudadanía, impulsando la concertación desde el aula. Para ello, debe
               definirse el siguiente título de la sesión:</q>
    <as r="R" correcta="1">
        <a>Describimos la ficha de entrevista sobre la celebración de la Semana Santa en su comunidad.</a>
        <a>Elaboramos una ficha de entrevista sobre la celebración de la Semana Santa.</a>
        <a>Reconocemos la estructura de una ficha de entrevista sobre la celebración de la Semana Santa en su
                comunidad.</a>
        <a>Investigamos la celebración de la Semana Santa en la localidad.</a>
    </as>
    <x>B.</x>
</p>

=== jiremv/preguntas/nom/5comunicacion/200-300_2019/nom-com-5286.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

  <q0>Para promover el intercambio de ideas sobre la lectura, el docente pide a los estudiantes que, en la pizarra,
      escriban un título que dé cuenta del tema central abordado conjuntamente en ambos textos. A continuación, se
      presentan las propuestas que escribieron tres estudiantes:</q0>
  <g0>5286-p.png</g0>
  <q>¿Cuál de las propuestas da cuenta del tema central abordado conjuntamente en los textos A y B?</q>
  <g></g>
  <q2></q2>
  <g2></g2>
  <as r="R" correcta="1">
    <a>La de Adela.</a>
    <a>La de Benito.</a>
    <a>La de Camila.</a>
  </as>
  <x>B</x>
  <i></i>
  <x2></x2>
  <i2></i2>
  <v1></v1>
</p>

=== jiremv/preguntas/nom/5comunicacion/100/nom-com-5035.xml
<?xml version="1.0" encoding="UTF-8" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

    <q0>Texto:</q0>
    <g0>5034-p.png</g0>
    <q>¿Cuál es la intención del texto propuesto?</q>
    <q2></q2>
    <as r="R" correcta="1">
        <a>Entretener</a>
        <a>Informar</a>
        <a>Criticar</a>
        <a>Argumentar</a>
    </as>
    <x>B.</x>
    <i></i>
    <x2></x2>
    <i2></i2>
    <v1></v1>
</p>

=== jiremv/preguntas/nom/0inicial/0-100_gratis/58.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd"
 
    <q0>Edgar y Daniel, del aula de cinco años, conversan. Edgar le cuenta a Daniel que ha aprendido a hacer aviones de
        papel. Emocionado, Daniel le pide que le enseñe. Entonces, rápidamente, Edgar coge un libro que está cerca y
        arranca una hoja. En ese momento, interviene la docente.<q0>
    <g0>58.png</g0>
    <q>En esta situación, ¿qué aprendizaje relacionado con el área de Personal Social está promoviendo la docente?</q>
    <g>></g>
    <as r="R" correcta="0">
        <a>Que los niños se aproximen a la noción de bien común.</a>
        <a>Que los niños propongan normas para cuidar los bienes del aula.</a>
        <a>Que los niños se comprometan a reparar el daño ocasionado por sus acciones.</a>
    </as>
    <x>A</x>
    <i></i>
    <x></x>
    <i></i>
    <v1></v1>
</p>

=== jiremv/preguntas/nom/5comunicacion/100/nom-com-5061.xml
<?xml version="1.0" encoding="UTF-8" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

    <q0></q0>
    <g0></g0>
    <q>Marca la correcta.</q>
    <q2></q2>
    <as r="R" correcta="3">
        <a>Los futbolistas entrenaron mucho para la final del partido; sin embargo; para mí, los resultados no fueron
           los que esperaba, José Villanueva, el entrenador.</a>
        <a>Los futbolistas entrenaron mucho para la final del partido; sin embargo para mí, los resultados no fueron los
           que esperaba José Villanueva, el entrenador.</a>
        <a>Los futbolistas entrenaron mucho para la final del partido; sin embargo, para mí los resultados no fueron los
           que esperaba José Villanueva, el entrenador.</a>
        <a>Los futbolistas entrenaron mucho para la final del partido; sin embargo, para mí, los resultados no fueron
           los que esperaba José Villanueva, el entrenador.</a>
    </as>
    <x>D.</x>
    <i></i>
    <x2></x2>
    <i2></i2>
    <v1></v1>
</p>

=== jiremv/preguntas/nom/1primaria/400-500/77.xml
<?xml version="1.0" encoding="UTF-8" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

    <q0>Juan, estudiante de 3° grado de EBR tiene dificultades para hacer un balance económico.</q0>
    <g0></g0>
    <q>Después de haber cumplido con ciertas encomendaciones de su señor padre, entonces:</q>
    <as r="R" correcta="1">
        <a>Juan carece de personalidad definida.</a>
        <a>Juan está presente frente a una situación problemática.</a>
        <a>Juan tiene que superar el obstáculo.</a>
        <a>Juan desconoce métodos adecuados de solución.</a>
    </as>
    <x>B.</x>
</p>

=== jiremv/preguntas/nom/2edfisicaprim/200-300_2019/2269.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

  <q0></q0>
  <g0>./../preguntas/nom/2edfisicaprim/200-300_2019/nom-efp-2268-p.png</g0>
  <q>¿Qué estilo de enseñanza está aplicando el docente cuando designa a algunos estudiantes como monitores?</q>
  <g></g>
  <q2></q2>
  <g2></g2>
  <as r="R" correcta="1">
    <a>Resolución de problemas.</a>
    <a>Enseñanza recíproca.</a>
    <a>Microenseñanza.</a>
  </as>
  <x>B</x>
  <i></i>
  <x2></x2>
  <i2></i2>
  <v1></v1>
</p>

=== jiremv/preguntas/nom/2edfisicaprim/200-300_2019/2279.xml
<?xml version="1.0" encoding="UTF-8" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

  <q0></q0>
  <g0></g0>
  <q>¿Qué información brinda la relación entre el peso y talla de los estudiantes, y su edad?</q>
  <g></g>
  <q2></q2>
  <g2></g2>
  <as r="R" correcta="1">
    <a>Información sobre su estado físico.</a>
    <a>Información sobre su estado nutricional.</a>
    <a>Información sobre su índice de masa corporal.</a>
  </as>
  <x>B</x>
  <i></i>
  <x2></x2>
  <i2></i2>
  <v1></v1>
</p>
