=== jiremv/preguntas/clase.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="p">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="q0"/>
        <xs:element type="xs:string" name="g0"/>
        <xs:element type="xs:string" name="q"/>
        <xs:element type="xs:string" name="g"/>
        <xs:element type="xs:string" name="q2"/>
        <xs:element type="xs:string" name="g2"/>
        <xs:element type="xs:string" name="q3"/>
        <xs:element type="xs:string" name="g3"/>
        <xs:element type="xs:string" name="q4"/>
        <xs:element type="xs:string" name="g4"/>
        <xs:element type="xs:string" name="q5"/>
        <xs:element type="xs:string" name="g5"/>
        <xs:element name="as">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="a" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="r" use="required"/>
            <xs:attribute type="xs:string" name="correcta" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:string" name="x"/>
        <xs:element type="xs:string" name="t"/>
        <xs:element type="xs:string" name="i"/>
        <xs:element type="xs:string" name="x2"/>
        <xs:element type="xs:string" name="i2"/>
        <xs:element type="xs:string" name="v1"/>
        <xs:element type="xs:string" name="d1"/>
        <xs:element type="xs:string" name="v2"/>
        <xs:element type="xs:string" name="d2"/>
        <xs:element type="xs:string" name="v3"/>
        <xs:element type="xs:string" name="d3"/>
        <xs:element type="xs:string" name="v4"/>
        <xs:element type="xs:string" name="d4"/>
        <xs:element type="xs:string" name="v5"/>
        <xs:element type="xs:string" name="d5"/>
        <xs:element type="xs:string" name="v6"/>
        <xs:element type="xs:string" name="d6"/>
        <xs:element type="xs:string" name="v7"/>
        <xs:element type="xs:string" name="d7"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jiremv/preguntas/nom/5comunicacion/200-300_2019/nom-com-5290.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

  <q0>Patricia, una de las estudiantes, ha expuesto la primera intervención que ha preparado para el debate frente a sus
      compañeros de equipo. Ellos le ofrecieron diversos comentarios sobre su texto oral. A continuación, se muestra la
      transcripción de tres de los comentarios:</q0>
  <g0>5290-p.png</g0>
  <q>¿Cuál de estos comentarios se centra en resaltar la utilización estratégica de recursos paraverbales en el texto
     oral de Patricia?</q>
  <g></g>
  <q2></q2>
  <g2></g2>
  <as r="R" correcta="2">
    <a>El 1.</a>
    <a>El 2.</a>
    <a>El 3.</a>
  </as>
  <x>C</x>
  <i></i>
  <x2></x2>
  <i2></i2>
  <v1></v1>
</p>

=== jiremv/preguntas/nom/5comunicacion/100-200_2018/nom-com-5187.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

    <q0></q0>
    <g0></g0>
    <q>Otro de los estudiantes le presentó a la docente el siguiente borrador de su texto:</q>
    <g>./../../preguntas/nom/5comunicacion/100-200_2018/nom-com-5187-p.png</g>
    <q2>¿Cuál de los siguientes problemas de coherencia presenta el texto del estudiante?</q2>
    <g2></g2>
    <as r="R" correcta="2">
        <a>Vacíos de información.</a>
        <a>Presencia de ideas contradictorias.</a>
        <a>Repetición innecesaria de algunas ideas.</a>
    </as>
    <x>C</x>
    <i></i>
    <x2></x2>
    <i2></i2>
    <v1></v1>
</p>

=== jiremv/preguntas/nom/2edfisicaprim/200-300_2019/2251.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

  <q0></q0>
  <g0></g0>
  <q>¿Qué enfoque transversal del currículo se evidencia principalmente en la intervención del docente?</q>
  <g></g>
  <q2></q2>
  <g2></g2>
  <as r="R" correcta="0">
    <a>Búsqueda de la excelencia.</a>
    <a>Orientación al bien común.</a>
    <a>Inclusivo o de atención a la diversidad.</a>
  </as>
  <x>A</x>
  <i></i>
  <x2></x2>
  <i2></i2>
  <v1></v1>
</p>

=== jiremv/preguntas/nom/5comunicacion/200/nom-com-5833.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

    <q0>Texto:</q0>
    <g0>5831-p.png</g0>
    <q>A partir de la lectura del gráfico, determine la alternativa correcta.</q>
    <q2></q2>
    <as r="R" correcta="1">
        <a>En el Perú, el índice de competitividad de las regiones de la sierra sur muestra un deterioro moderado en los
           últimos años.</a>
        <a>En cuanto a los resultados competitividad regional, existe una brecha significativa entre la capital y el
           resto del país.</a>
        <a>La región del Callao ha tenido los mejores resultados de competitividad en comparación con la capital del
           país.</a>
        <a>Las regiones de Cajamarca y Amazonas han disminuido su producción agropecuaria en los últimos tres años.</a>
        <a>Hay un centralismo político y administrativo en la ciudad de Lima y en las diversas capitales de provincia.</a>
    </as>
    <x>B.</x>
    <i></i>
    <x2>Con relación a los resultados de competitividad regional, resulta correcto aseverar que existe una brecha
        significativa, o sea, una notoria diferencia entre la capital y el resto del país. En el gráfico podemos notar
        que Lima presenta un índice de 73,43 en el 2016, muy por encima de regiones como Arequipa (43,44), Ayacucho
        (26,84) y Huancavelica (20). Por lo tanto, podemos confirmar que la diferencia entre estas cifras es muy
        significativa.</x2>
    <i2></i2>
    <v1></v1>
</p>

=== jiremv/preguntas/nom/4cta/200-300_2019/nom-cta-4257.xml
<?xml version="1.0" encoding="UTF-8" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

    <q0>Lea la siguiente situación y responda</q0>
    <g0>4254-p.png</g0>
    <q>El docente ha identificado aspectos que los estudiantes aún deben mejorar en su plan de indagación. ¿Qué grupo de
       preguntas es pertinente que plantee el docente para retroalimentar a los estudiantes sobre estos aspectos?</q>
    <g></g>
    <q2></q2>
    <g2></g2>
    <as r="R" correcta="2">
        <a>¿En qué rango de tiempo se llevará a cabo cada reacción? ¿En cuál de los ensayos ocurrirá más rápido la
           reacción?</a>
        <a>¿Qué sucederá si emplean otro tipo de antiácido? ¿Cómo cambiará la velocidad de la reacción si disminuyen la
           temperatura?</a>
        <a>¿Cuáles son las posibles fuentes de error de su indagación y cómo pueden reducirlas? ¿Cómo pueden evaluar la
           confiabilidad de sus resultados?</a>
    </as>
    <x>C</x>
    <i></i>
    <x2></x2>
    <i2></i2>
    <v1></v1>
</p>

=== jiremv/preguntas/nom/5comunicacion/100/nom-com-5040.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

    <q0>Texto:</q0>
    <g0>5034-p.png</g0>
    <q>Se puede afirmar:</q>
    <q2></q2>
    <as r="R" correcta="3">
        <a>El rey Luis XV realmente se enamoró de su antigua amante.</a>
        <a>En la festividad, solo las mujeres de las clases altas portaban un pañuelo.</a>
        <a>El rey portaba una máscara, él era la única persona que cubría su rostro.</a>
        <a>Mujeres de todas las clases tenían las mismas oportunidades de convertirse en la próxima amante del rey.</a>
    </as>
    <x>D.</x>
    <i></i>
    <x2></x2>
    <i2></i2>
    <v1></v1>
</p>

=== jiremv/preguntas/nom/0inicial/0-100_gratis/65.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">
 
    <q>0>Los niños y la docente del aula de cuatro años se encuentran limpiando el huerto de la IE. Durante la actividad,
        los niños recogen diversos objetos como piedras, ramas, hojas, etc. Entonces, la docente decide aprovechar esa
        situación para promover la clasificación en los niños.</q>0>
    <g0></g0>
    <q>¿Cuál de las siguientes acciones es más pertinente para ese propósito?</q>
    <g</g
    <q></q>
    <g2</g2
    <as> r="R" correcta="0"
        <a>Plantearles que agrupen los objetos recolectados según lo deseen y, luego, preguntarles por qué los agruparon
           de ese modo.</a>
        <a>Entregarles cajas etiquetadas según los objetos recolectados y, luego, pedirles que los guarden en las cajas
           según corresponda.</a>
        <a>Explicarles que clasificar es juntar objetos que se parecen y, luego, darles un ejemplo de cómo hacerlo para
           que ellos continúen agrupando los demás objetos.</a>
    </as>
    <x>A</x>
    <i></i>
    <x></x>
    <i></i>
    <v1></v1>
</p>

=== jiremv/preguntas/nom/3arte/100-200_2018/76.xml
<?xml version="1.0" encoding="UTF-8" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

    <q0></q0>
    <g0></g0>
    <q>¿Qué es una "triada" en teoría musical?</q>
    <g></g>
    <q2></q2>
    <g2></g2>
    <as r="R" correcta="0">
        <a>Un acorde compuesto por tres notas.</a>
        <a>Una organización del pulso en tres tiempos por compás.</a>
        <a>Una subdivisión del tiempo en tres unidades iguales en compases simples.</a>
    </as>
    <x>A</x>
    <i></i>
    <x2></x2>
    <i2></i2>
    <v1></v1>
</p>
