=== jiremv/preguntas/clase.dtd
<?xml encoding="iso-8859-1"?>
<!-- Fichero de definción de cada pregunta -->
<!ELEMENT p (q0*, g0*, q, g*, q2*, g2*,as, x, t*, i*, x2*, i2*, v1*, d1*, v2*, d2*, v3*, d3*, v4*, d4*, v5*, d5*, v6*, d6*, v7*, d7*)>
<!ELEMENT q0 (#PCDATA)>
<!ELEMENT g0 (#PCDATA)>
<!ELEMENT q (#PCDATA)>
<!ELEMENT g (#PCDATA)>
<!ELEMENT q2 (#PCDATA)>
<!ELEMENT g2 (#PCDATA)>
<!ELEMENT as (a)+>
<!ATTLIST as
	r CDATA #REQUIRED
	correcta CDATA #REQUIRED
>
<!ELEMENT a (#PCDATA)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT t (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT x2 (#PCDATA)>
<!ELEMENT i2 (#PCDATA)>
<!ELEMENT v1 (#PCDATA)>
<!ELEMENT d1 (#PCDATA)>
<!ELEMENT v2 (#PCDATA)>
<!ELEMENT d2 (#PCDATA)>
<!ELEMENT v3 (#PCDATA)>
<!ELEMENT d3 (#PCDATA)>
<!ELEMENT v4 (#PCDATA)>
<!ELEMENT d4 (#PCDATA)>
<!ELEMENT v5 (#PCDATA)>
<!ELEMENT d5 (#PCDATA)>
<!ELEMENT v6 (#PCDATA)>
<!ELEMENT d6 (#PCDATA)>
<!ELEMENT v7 (#PCDATA)>
<!ELEMENT d7 (#PCDATA)>

=== jiremv/preguntas/nom/1primaria/0-100_gratis_pobre/nom-pri-1006.xml
<?xml version='1.0' encoding='iso-8859-1'?> 
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
<q0>La docente de primer grado sienta a Francisco frente a una maqueta en la que hay varias
montañas Luego, le muestra diversas fotografías tomadas desde diversos ángulos,
preguntándole: ¿Cuáles de ellas has visto? Al responder, Francisco describe aquellas que
muestran las montañas que él ve y no las que vería una persona sentada en frente o al lado
posterior.</q0>
  <q>
 ¿Qué característica del pensamiento se evidencia en la respuesta de Francisco?
  </q>
  <as r="R" correcta="2">
    <a>
    Transitividad.
    </a><a>
    Conservación.
    </a><a>
    Egocentrismo.
    </a><a>
    Irreversibilidad.
    </a>
  </as>
  <x>
C.
</x>
</p>

=== jiremv/preguntas/nom/1primaria/300-400_simulacro/nom-pri-1308.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
  <q0></q0>
  <g0>./../../preguntas/nom/1primaria/200-300_simulacro/nom-pri-1306-p.png</g0>
  <q>En el texto, ¿cuál de los siguientes hechos es una consecuencia del 'efecto de burbuja'?</q>
  <g></g>
  <q2></q2>
  <g2></g2>
  <as r="R" correcta="2">
    <a>Las redes sociales ajustan los contenidos que muestran según las búsquedas previas de los usuarios.</a>
    <a>La prensa y la televisión pierden audiencia frente a los medios digitales, sobre todo entre los jóvenes.</a>
    <a>Las redes sociales ayudan a que las teorías conspirativas persistan y crezcan en el espacio virtual.</a>
  </as>
  <x>C</x>
  <i></i>
  <x2></x2>
  <i2></i2>
  <v1></v1>
</p>

=== jiremv/preguntas/nom/5comunicacion/100-200_2018/nom-com-5180.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
    <q0></q0>
    <g0></g0>
    <q>Los estudiantes están preparándose para exponer, ante la comunidad educativa, cómo mejorar el tratamiento de
       residuos sólidos. Durante la explicación del docente sobre los aspectos que deben considerar en una exposición
       (como adecuar el texto a la audiencia, usar recursos expresivos, ordenar sus ideas en torno al tema, entre
       otros), un estudiante interviene diciendo:</q>
    <g>./../../preguntas/nom/5comunicacion/100-200_2018/nom-com-5180-p.png</g>
    <q2>¿Qué prejuicio sobre la exposición oral se evidencia en la intervención del estudiante?</q2>
    <g2></g2>
    <as r="R" correcta="0">
        <a>Una exposición puede llevarse a cabo sin haber planificado las ideas previamente.</a>
        <a>Durante una exposición, la memoria sirve para transmitir la información recopilada.</a>
        <a>En una exposición, los recursos visuales pueden ayudar al público en la comprensión del tema.</a>
    </as>
    <x>A</x>
    <i></i>
    <x2></x2>
    <i2></i2>
    <v></v>
</p>

=== jiremv/preguntas/nom/11english/300-400_2018/nom-eng-11387.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
  <q0></q0>
  <g0></g0>
  <q>Read the first sentence and choose the correct alternative to complete the second sentence so that it means the
     same as the first. Sentence 1: Stop interrupting me all the time! Sentence 2: I wish you _____________ me.</q>
  <g></g>
  <q2></q2>
  <g2></g2>
  <as r="R" correcta="1">
    <a>don't interrupt</a>
    <a>wouldn't interrupt</a>
    <a>shouldn't interrupt</a>
  </as>
  <x>B</x>
  <i></i>
  <x2></x2>
  <i2></i2>
  <v1></v1>
</p>

=== jiremv/preguntas/nom/7trabajo/100-200_2018/nom-tra-7164.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
  <q0></q0>
  <g0></g0>
  <q>Considerando el análisis FODA de una empresa de servicios, ¿cuál de las siguientes alternativas corresponde a una
     amenaza?</q>
  <g></g>
  <q2></q2>
  <g2></g2>
  <as r="R" correcta="0">
    <a>Contar con empresas similares en la localidad que tienen mayor experiencia en el rubro.</a>
    <a>Tener poco personal para atender la alta demanda del servicio en su localidad.</a>
    <a>Poseer recursos limitados para realizar publicidad masiva en su localidad.</a>
  </as>
  <x>A</x>
  <i></i>
  <x2></x2>
  <i2></i2>
  <v></v>
</p>

=== jiremv/preguntas/nom/5comunicacion/200-300_2019/nom-com-5271.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
  <q0></q0>
  <g0>./../preguntas/nom/5comunicacion/200-300_2019/nom-com-5271-p.png</g0>
  <q>Para ayudar a los estudiantes en la comprensión del sentido del texto, la docente ha propuesto varias preguntas.</q>
  <g></g>
  <q2>¿Cuál de las siguientes preguntas es más adecuada para que los estudiantes obtengan información explícita?</q2>
  <g2></g2>
  <as r="R" correcta="2">
    <a>¿Con qué partes de su cuerpo se alimenta el caracol?</a>
    <a>¿Por qué el caracol se contrae al interior de su concha?</a>
    <a>¿Qué le permite al caracol deslizarse mejor sobre las hojas?</a>
  </as>
  <x>C</x>
  <i></i>
  <x2></x2>
  <i2></i2>
  <v></v>
</p>

=== jiremv/preguntas/nom/1primaria/300-400_simulacro/nom-pri-1307.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
  <q0></q0>
  <g0>./../../preguntas/nom/1primaria/200-300_simulacro/nom-pri-1306-p.png</g0>
  <q>En el texto, ¿a qué se refiere la noción de 'posverdad'?</q>
  <g></g>
  <q2></q2>
  <g2></g2>
  <as r="R" correcta="0">
    <a>A un contexto en el que las noticias se aceptan cuando se ajustan a los marcos de creencias de quienes las
       adoptan, sin importar su veracidad.</a>
    <a>A un tipo de noticias que se difunden a través de los medios de comunicación, independientemente de su veracidad.</a>
    <a>A la capacidad de evaluar la veracidad de la información nueva proveniente de las redes sociales y otros medios
       digitales.</a>
  </as>
  <x>A</x>
  <i></i>
  <x2></x2>
  <i2></i2>
  <v1></v1>
</p>

=== jiremv/preguntas/nom/11english/300-400_2018/nom-eng-11362.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
  <q0></q0>
  <g0>./../../preguntas/nom/11english/300-400_2018/nom-eng-11357-p1.png</g0>
  <q>Sophia has planned to give her students a communicative post-reading task. Given the teacher's goal, which activity
     is least appropriate for her purpose?</q>
  <g></g>
  <q2></q2>
  <g2></g2>
  <as r="R" correcta="0">
    <a>The teacher tells the students to choose their favorite character and draw it on a piece of paper. Then the
       teacher asks some volunteers to come to the front and describe the drawings.</a>
    <a>The teacher asks the students to work in pairs to create a conversation between the fox and the crow. They write
       the conversation, practice it for some minutes and present it in front of the class.</a>
    <a>The teacher groups the students and tells them to change some details of the story in order to make a new version
       of it. The students discuss, put their ideas together and narrate the new version of the fable to the class.</a>
  </as>
  <x>A</x>
  <i></i>
  <x2></x2>
  <i2></i2>
  <v1></v1>
</p>
