=== jiremv/preguntas/clase.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="p">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="q0"/>
        <xs:element type="xs:string" name="g0"/>
        <xs:element type="xs:string" name="q"/>
        <xs:element type="xs:string" name="g"/>
        <xs:element type="xs:string" name="q2"/>
        <xs:element type="xs:string" name="g2"/>
        <xs:element type="xs:string" name="q3"/>
        <xs:element type="xs:string" name="g3"/>
        <xs:element type="xs:string" name="q4"/>
        <xs:element type="xs:string" name="g4"/>
        <xs:element type="xs:string" name="q5"/>
        <xs:element type="xs:string" name="g5"/>
        <xs:element name="as">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="a" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="r" use="required"/>
            <xs:attribute type="xs:string" name="correcta" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:string" name="x"/>
        <xs:element type="xs:string" name="t"/>
        <xs:element type="xs:string" name="i"/>
        <xs:element type="xs:string" name="x2"/>
        <xs:element type="xs:string" name="i2"/>
        <xs:element type="xs:string" name="v1"/>
        <xs:element type="xs:string" name="d1"/>
        <xs:element type="xs:string" name="v2"/>
        <xs:element type="xs:string" name="d2"/>
        <xs:element type="xs:string" name="v3"/>
        <xs:element type="xs:string" name="d3"/>
        <xs:element type="xs:string" name="v4"/>
        <xs:element type="xs:string" name="d4"/>
        <xs:element type="xs:string" name="v5"/>
        <xs:element type="xs:string" name="d5"/>
        <xs:element type="xs:string" name="v6"/>
        <xs:element type="xs:string" name="d6"/>
        <xs:element type="xs:string" name="v7"/>
        <xs:element type="xs:string" name="d7"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jiremv/preguntas/nom/0inicial/100-200_2018/89.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

    <q0></q0>
    <g0>./../../preguntas/nom/0inicial/100-200_2018/nom-ini-188-p.png</g0>
    <q>¿Cuál de las siguientes preguntas es pertinente para que los niños realicen inferencias sobre este fragmento?</q>
    <q2></q2>
    <as r="R" correcta="1">
        <a>¿Cómo eran las barbas del viejo bagre?</a>
        <a>¿Por qué se sentía orgulloso el viejo bagre?</a>
        <a>¿Qué piensan de la preocupación de la mamá del bagrecico?</a>
    </as>
    <x>B.</x>
    <i></i>
    <x2></x2>
    <i2></i2>
    <v1></v1>
</p>

=== jiremv/preguntas/nom/3arte/100-200_2018/78.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

    <q0></q0>
    <g0></g0>
    <q>El renombrado compositor y productor musical Brian Eno (Inglaterra, 1948) dijo lo siguiente sobre los
       secuenciadores digitales y la democratización de la producción musical: "El gran beneficio de los secuenciadores
       computarizados es que eliminan el problema de la habilidad y lo reemplazan por el problema del discernimiento".</q>
    <g></g>
    <q2>¿Cuál de las siguientes afirmaciones es la idea principal de lo expresado por Brian Eno?</q2>
    <g2></g2>
    <as r="R" correcta="1">
        <a>Los secuenciadores digitales introducen interfaces de usuario más amigables que eliminan la necesidad de
           dominar software complejo y liberan el tiempo del usuario para dedicarlo al desarrollo y acabado de sus
           productos musicales.</a>
        <a>Los secuenciadores digitales permiten que una persona aborde la composición de obras de todo nivel de
           complejidad, siendo más importantes su imaginación y su inventiva que su capacidad para tocar instrumentos
           musicales.</a>
        <a>Los secuenciadores digitales introducen una multiplicidad de herramientas y opciones para la producción
           musical digital, por lo cual es muy importante que las personas usen su criterio y experiencia para
           distinguir qué herramientas usar y cuáles dejar de lado en un momento determinado.</a>
    </as>
    <x>B</x>
    <i></i>
    <x2></x2>
    <i2></i2>
    <v1></v1>
</p>

=== jiremv/preguntas/nom/2edfisicaprim/0-100_gratis/2065.xml
<?xml version="1.0" encoding="UTF-8" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

    <q0></q0>
    <g0></g0>
    <q>¿Qué competencia se está desarrollando predominantemente en la sesión descrita?</q>
    <g></g>
    <q2></q2>
    <g2></g2>
    <as r="R" correcta="0">
        <a>¿Qué competencia se está desarrollando predominantemente en la sesión descrita?</a>
        <a>Interactúa a través de sus habilidades sociomotrices.</a>
        <a>Se desenvuelve de manera autónoma a través de su motricidad.</a>
    </as>
    <x>A</x> <v1></v1>
    <i></i>
    <x2></x2>
    <i2></i2>
    <v></v>
</p>

=== jiremv/preguntas/nom/1primaria/400-500/25.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

    <q0>El profesor Luis, en la clase de matemática, guía, explora y respalda las iniciativas de sus
                estudiantes, sin dar la clase de manera frontal tipo conferencia,</q0>
    <q>esto evidencia...</q>
    <as r="R" correcta="3">
        <a>Dominio de saberes diarios.</a>
        <a>Adecuado desempeño docente.</a>
        <a>Dominio en la resolución de situaciones problemáticas.</a>
        <a>Experiencia como docente.</a>
    </as>
    <x>D.</x>
</p>

=== jiremv/preguntas/nom/5comunicacion/200-300_2019/nom-com-5257.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

  <q0>Una docente está revisando los textos narrativos que han escrito los estudiantes. En muchos casos, ella nota que
      el uso inadecuado de los signos de puntuación dificulta la comprensión de la trama de dichos textos.</q0>
  <g0></g0>
  <q></q>
  <g></g>
  <q2></q2>
  <g2></g2>
  <as r="R" correcta="1">
    <a>Organizar a los estudiantes en parejas para que intercambien sus textos y los lean. Luego, pedir que encierren en
       un círculo los errores en el uso de los signos de puntuación que encuentren para que el autor del texto los
       corrija.</a>
    <a>Solicitar que uno de los estudiantes comparta su texto voluntariamente para analizarlo en la pizarra. Luego,
       pedir que identifiquen los signos de puntuación y que expliquen cuáles creen que dificultan la comprensión del
       escrito.</a>
    <a>Entregar a cada estudiante un texto cuyos signos de puntuación se han omitido deliberadamente. Luego, leer con
       ellos dicho texto, indicándoles dónde deberían colocarse dichos signos para que el lector comprenda el mensaje.</a>
  </as>
  <x>B</x>
  <i></i>
  <x2></x2>
  <i2></i2>
  <v1></v1>
</p>

=== jiremv/preguntas/nom/3arte/200-300_2019/12.xml
<?xml version="1.0" encoding="UTF-8" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

    <q0>Después de mostrarles la acuarela de Pancho Fierro a los estudiantes, el docente de Arte y Cultura les enseña
        otra imagen de la misma danza, pero ejecutada en la época actual, para que las comparen y así conozcan la
        evolución de la danza en el tiempo.</q0>
    <g0></g0>
    <q>¿Cuál de los siguientes grupos de preguntas es el más adecuado para iniciar el análisis de las imágenes con los
       estudiantes?</q>
    <g></g>
    <q2></q2>
    <g2></g2>
    <as r="R" correcta="0">
        <a>¿Qué les llama más la atención de la imagen actual de la danza? ¿Qué semejanzas y diferencias encuentran en
           el vestuario de ambas imágenes? ¿Y entre las máscaras utilizadas antiguamente y las actuales? ¿Qué
           instrumentos musicales observan en cada imagen?</a>
        <a>¿Qué género de danza se visualiza en las imágenes? ¿Cómo es la postura corporal de los bailarines en cada
           imagen? ¿Cuál es el contexto histórico de la primera imagen? ¿Cuál es el contexto histórico de la segunda
           imagen? ¿Qué valor cultural tiene esta danza?</a>
        <a>¿Habían escuchado hablar de esta danza? ¿Han visto bailar esta danza antes? ¿Por qué el vestuario actual es
           diferente? ¿Los personajes siguen llevando máscara en la actualidad? ¿Conocen el mensaje de la danza?</a>
    </as>
    <x>A</x>
    <i></i>
    <x2></x2>
    <i2></i2>
    <v1></v1>
</p>

=== jiremv/preguntas/nom/1primaria/100-200_2018/62.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

	<q0>Aprovechando que en la IE se ha realizado hace poco la final del campeonato de fútbol en el
marco de las olimpiadas escolares, un docente del ciclo IV ha decidido aprovechar la situación
para realizar la siguiente actividad:</q0>
	<g0>62-p.png</g0>
	<q>Si el propósito del docente es favorecer que los estudiantes se inicien en el desarrollo de la
capacidad de interpretación crítica de fuentes,</q>
	<q2>¿por qué la actividad planteada es pertinente
para este propósito?</q2>
	<as r="R" correcta="2">
		<a>Porque ayuda a que los estudiantes expliquen por qué los testimonios orales pueden ser
fuentes menos fiables que las fuentes escritas.</a>
		<a>Porque ayuda a que los estudiantes identifiquen fuentes que ofrecen relatos auténticos
para explicar un determinado hecho.</a>
		<a>Porque ayuda a que los estudiantes reconozcan que de un mismo hecho pueden derivarse
diferentes narraciones sobre él.</a>
	</as>	
	<x>C.</x>
	<i></i>
	<x2>
	</x2>
	<i2></i2>
	<v1></v1>
</p>

=== jiremv/preguntas/nom/1primaria/400-500/58.xml
<?xml version="1.0" encoding="UTF-8" ?>
<p xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./../../../clase.xsd">

    <q0>El docente responsable de un aula ha sistematizado los resultados de la evaluación de segundo grado "B".
                A partir de estos resultados realiza las siguientes actividades: entrega las calificaciones a sus
                estudiantes y a los padres de familia, les explica de manera individual en qué aspectos deben mejorar,
                replantea algunas estrategias y métodos en su proceso de enseñanza y entrega una carta de reconocimiento
                a los que obtuvieron las notas más altas.</q0>
    <g0></g0>
    <q>Los estudiantes toman conciencia y, al final del año escolar, la mayoría de ellos mejoró
               significativamente sus resultados. ¿Qué funciones y finalidades de la evaluación se evidencian en las
               acciones del docente?</q>
    <as r="R" correcta="0">
        <a>Pedagógica y social, formativa e informativa.</a>
        <a>Sumativa y formativa, social e Informativa.</a>
        <a>Sistemática e informativa, participativa y social.</a>
    </as>
    <x>A.</x>
</p>
