=== jiremv/preguntas/clase.dtd
<?xml encoding="iso-8859-1"?>
<!-- Fichero de definción de cada pregunta -->
<!ELEMENT p (q0*, g0*, q, g*, q2*, g2*,as, x, t*, i*, x2*, i2*, v1*, d1*, v2*, d2*, v3*, d3*, v4*, d4*, v5*, d5*, v6*, d6*, v7*, d7*)>
<!ELEMENT q0 (#PCDATA)>
<!ELEMENT g0 (#PCDATA)>
<!ELEMENT q (#PCDATA)>
<!ELEMENT g (#PCDATA)>
<!ELEMENT q2 (#PCDATA)>
<!ELEMENT g2 (#PCDATA)>
<!ELEMENT as (a)+>
<!ATTLIST as
	r CDATA #REQUIRED
	correcta CDATA #REQUIRED
>
<!ELEMENT a (#PCDATA)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT t (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT x2 (#PCDATA)>
<!ELEMENT i2 (#PCDATA)>
<!ELEMENT v1 (#PCDATA)>
<!ELEMENT d1 (#PCDATA)>
<!ELEMENT v2 (#PCDATA)>
<!ELEMENT d2 (#PCDATA)>
<!ELEMENT v3 (#PCDATA)>
<!ELEMENT d3 (#PCDATA)>
<!ELEMENT v4 (#PCDATA)>
<!ELEMENT d4 (#PCDATA)>
<!ELEMENT v5 (#PCDATA)>
<!ELEMENT d5 (#PCDATA)>
<!ELEMENT v6 (#PCDATA)>
<!ELEMENT d6 (#PCDATA)>
<!ELEMENT v7 (#PCDATA)>
<!ELEMENT d7 (#PCDATA)>

=== jiremv/preguntas/nom/7trabajo/100-200_2018/60.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
  <q0></q0>
  <g0></g0>
  <q>¿Cuál de las siguientes afirmaciones expresa una de las características del modelo de negocio LEAN CANVAS?</q>
  <g></g>
  <q2></q2>
  <g2></g2>
  <as r="R" correcta="2">
    <a>Su foco está en los clientes y en la relación con ellos.</a>
    <a>Sus aspectos o módulos tienen mayor dependencia entre sí.</a>
    <a>Su prioridad está en la aportación de valor de los productos.</a>
  </as>
  <x>C</x>
  <i></i>
  <x2></x2>
  <i2></i2>
  <v></v>
</p>

=== jiremv/preguntas/nom/0inicial/300-400/nom-ini-324.xml
<?xml version='1.0' encoding='iso-8859-1'?> 
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
    <q>Carmen llega al aula de inicial y encuentra que varios de sus niños están esperándola deseosos de jugar 
    en los sectores del aula. Los niños se inquietan cada vez más al ver llegar a otros compañeritos y se resisten a
    permanecer sentados, por tal motivo la profesora decide dejarlos jugar de manera libre confiando en la seguridad 
    de los sectores. Al pasar 30 minutos entona una canción para que guarden los juguetes y empezar el tema del día: 
    "Los medios de transporte". ¿Qué tipo de materiales son pertinentes para lograr el propósito de la sesión?
</q>
    <as r="R" correcta="1">
        <a>Material estructurado.</a>
        <a>Material estructurado y no estructurado.</a>
        <a>Material no estructurado.</a>
        <a>Juguetes.</a>
    </as>
    <x>B.</x>
</p>

=== jiremv/preguntas/nom/11english/100-200_2018/nom-eng-11169.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
    <q0></q0>
    <g0></g0>
    <q>Roberta's students have been working on different kinds of writing products during the past few months. She has
       planned the following sequence to reinforce her students' writing skills:</q>
    <g>./../../preguntas/nom/11english/100-200_2018/nom-eng-11169-p.png</g>
    <q2>Based on the sequence above, which of the following methods to teaching writing has Roberta adopted?</q2>
    <g2></g2>
    <as r="R" correcta="1">
        <a>Task-Based Learning.</a>
        <a>Problem-Based Learning.</a>
        <a>Presentation-Practice-Production.</a>
    </as>
    <x>B</x>
    <i></i>
    <x2></x2>
    <i2></i2>
    <v></v>
</p>

=== jiremv/preguntas/nom/0inicial/300-400/nom-ini-326.xml
<?xml version='1.0' encoding='iso-8859-1'?> 
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
    <q>En un aula de inicial se observa que los niños y niñas se desenvuelven con tranquilidad, alegres y actúan
    de forma espontánea. La docente se muestra tranquila y de vez en cuando recalca las normas de convivencia en tono 
    suave. ¿Qué refleja esta situación?
</q>
    <as r="R" correcta="2">
        <a>La docente no interviene y permite que los niños realicen actividades libres.</a>
        <a>La docente tiene poca paciencia con los niños y niñas.</a>
        <a>La docente promueve un clima de buen trato.</a>
        <a>La docente es muy cariñosa con algunos niños y niñas.</a>
    </as>
    <x>C.</x>
</p>

=== jiremv/preguntas/nom/4cta/100-200_2018/nom-cta-4158.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
	<q0>
	</q0>
	<g0>./../../preguntas/nom/4cta/100-200_2018/nom-cta-4158-p.png
	</g0>
	<q>¿A cuál de las siguientes preguntas se busca responder con los resultados que se presentan
en los gráficos?
	</q>
	<q2>	
	</q2>
	<as r="R" correcta="1">
		<a>¿Qué relación existe entre las concentraciones de glucosa y lactato en la sangre de una
persona?</a>
		<a>¿Qué diferencias hay entre las concentraciones de glucosa y lactato en la sangre de una
persona al inicio y fin de una actividad deportiva intensa?</a>
		<a>¿Por qué las concentraciones de glucosa y lactato en la sangre de las personas cambian
luego de realizar una actividad deportiva intensa?</a>
	</as>	
	<x>B.</x>
	<i></i>
	<x2>
	</x2>
	<i2></i2>
	<v></v>
</p>

=== jiremv/preguntas/nom/8religion/100-200_2018/nom-rel-8171.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
  <q0></q0>
  <g0></g0>
  <q>¿A qué paso de la Lectio Divina corresponden las siguientes preguntas?</q>
  <g>./../../preguntas/nom/8religion/100-200_2018/nom-rel-8171-p.png</g>
  <q2></q2>
  <g2></g2>
  <as r="R" correcta="2">
    <a>Lectura</a>
    <a>Meditación</a>
    <a>Contemplación</a>
  </as>
  <x>C</x>
  <i></i>
  <x2></x2>
  <i2></i2>
  <v></v>
</p>

=== jiremv/preguntas/nom/0inicial/300-400/nom-ini-349.xml
<?xml version='1.0' encoding='iso-8859-1'?> 
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
    <q>Los niños de 4 años cuando juegan les cuesta devolver las cosas que han usado, dejándolas tiradas en el 
    aula. ¿Qué debe hacer la profesora?
</q>
    <as r="R" correcta="0">
        <a>Llegar a acuerdos con los niños, acompañarlos en el establecimiento del hábito y realizar un seguimiento.</a>
        <a>Pedir al personal de limpieza que recojan las cosas ya que los niños son muy pequeños para hacerlo.</a>
        <a>Decirle a los niños que se sienten y que ella va a recoger todo más rápido y poder así empezar la clase.</a>
        <a>Decirle a los niños que los que recojan y acomodan más cosas, que luego serán premiados por su colaboración.</a>
    </as>
    <x>A.</x>
</p>

=== jiremv/preguntas/nom/1primaria/100-200_2018/nom-pri-1169.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE pregunta SYSTEM "./../../../clase.dtd">
<p>
	<q0>Lea las siguientes situaciones:
	</q0>
	<g0>./../../preguntas/nom/1primaria/100-200_2018/nom-pri-1169-p.png
	</g0>
	<q>A partir de lo descrito en cada situación, ¿cuál de ellas constituye un dilema moral?
	</q>
	<q2>	
	</q2>
	<as r="R" correcta="1">
		<a>La situación I.</a>
		<a>La situación II.</a>
		<a>La situación III.</a>
	</as>	
	<x>B.</x>
	<i></i>
	<x2>
	</x2>
	<i2></i2>
	<v></v>
</p>
